### ISSUE TITLE
Using with metalsmith-permalinks

### ISSUE THREAD

**Issue by olimsaidov** [RobinThrift/metalsmith-paginate#1]
How can use this plugin with metalsmith-permalinks?

**Comment by RobinThrift** [comment]
You can use this with the paginate plugin, however your pagination files (the ones, that display the items, page for page) mustn't be affected by the plugin. 
So if you have your permalink structure set up as `":title"`, then make sure, you don't give your pagination files a title attribute. 

This is a little incompatibility I will fix soon! I use the file path atm, to basically clone the files. This could also be done, with the paginate plugin active, I would just have to look out for it! I might change a few things internally anyway, so look out for an update soon!
